### ISSUE TITLE
filebeat iptables module conflicts with syslog

### ISSUE THREAD

**Issue by truekonrads** [fastlorenzo/redelk-client#3]
This error shows that iptables tries to listen to same port as syslog - 9001
```
Mar  8 07:12:51 xxx filebeat[112836]: 2022-03-08T07:12:51.397Z#011ERROR#011[syslog]#011syslog/input.go:154#011Error starting the servererrorlisten udp 127.0.0.1:9001: bind: address already in use
```
If only iptables or syslog are enabled, there is no error. If both - there is an error. I'm not clear why would you need iptables module in this setup at all.

**Comment by fastlorenzo** [comment]
Thanks for the catch, removed the iptables module
